
project_id = "nhljzyqmvvwobkyusuxp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[realtime]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[functions]
analyze-design = {}
screenshot-url = {}
analyze-design-openai = {}
