// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhljzyqmvvwobkyusuxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5obGp6eXFtdnZ3b2JreXVzdXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzUyOTEsImV4cCI6MjA1NjE1MTI5MX0.mH7laJluvOYdrFbfSZCCnHYm2yrlrW-kGQeoPyeIUCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);